### PR TITLE
Spring/Summer refresh

### PR DESCRIPTION
**Pull request by gichiba**
This is a collection of minor tweaks and phrasing adjustments that I've been poking along at for months, hence the title "spring refresh" even though the summer's nearly gone! 

The biggest change is that the Merkle Tree article is finally published on ethereum.org with a better beginner-friendly introduction, so we can finally link to it (whereas before, it would drop you into an awkward description of RLP-encoding). 

I may want to submit more, but I am worried if I wait too long on this the Verkle tree will have already been planted! Best to just get these out and then fold any subsequent edits in with the next major site update. 

Just for avoidance of doubt: I'm the author of the original story so these changes are pre-approved :heavy_check_mark:

### CODE REVIEW

**Comment by gichiba** [comment]
*cough* @pettinarip could I ask you to look it over and merge if there are no errors?

**Comment by pettinarip** [comment]
Hey @gichiba LGTM but there are two conflicts blocking me from merging the PR.
image

LMK if you can fix it or if you need help.

**Comment by gichiba** [comment]
Hmmm it seems that something has changed with the way links are handled, and `ReferenceError: MouseDownLink is not defined` is what comes through in the error. 

I know it'd be possible to manually change all these links but I can't help but think there's some kind of `lint` command that needs to be run... @pettinarip I would appreciate your help after all -- I worry I'll do more damage if I continue to force push with abandon

**Review by pettinarip — APPROVED** [review]
LGTM!

**Pull request merged**
