### PR TITLE
Lossless image optimization

### PR DESCRIPTION
**Pull request by FlipFloop**

### CODE REVIEW

**Comment by samajammin** [comment]
Hey @FlipFloop - thanks for the PR! Could you please rebase this off the latest `master` to resolve the merge conflicts? It should also fix your preview build.

**Comment by FlipFloop** [comment]
Sure! Doing it right now!

**Comment by samajammin** [comment]
Hey @FlipFloop - checking in on this. Thanks!

**Comment by samajammin** [comment]
@FlipFloop closing this for now. Please feel free to re-open once you address the merge conflicts. Thanks!

**Pull request closed without merging**
